title: Olá Seja Bem Vindo ao meu Mundo! Eu sou Take
description: > # this means to ignore newlines until "baseurl:"
  Laboratório de scripts, html,css,css3,jquery,wordpress, dicas, plugins
  e tudo que irei testar de programação.
permalink: ':title/'
baseurl: "/takashi-ichikihara.github.io/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: tkmaster0101 #if your site has a twitter account, enter it here

# Author Settings
author: Takashi Ichikihara # add your name
author-img: avatar_take.png # add your photo
about-author: Eu sou um desenvolvedor web focado no desenvolvimento de front-end. Sempre com fome para continuar aprendendo.  # add description
twitter: tkmaster0101 # add your Twitter handle
facebook: caradeanime # add your Facebook handle
github: takashi-ichikihara # add your Github handle
linkedin: elison-takashi-ichikihara-ab863232 # add your Linkedin handle
email: contato@studiomugen.com.br # add your Email address

# Disqus
discus-identifier: https-takashi-ichikihara-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
